apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.secretName | quote }}
spec:
  acme: 
    email: {{ .Values.adminEmail | quote }} 
    privateKeySecretRef:
      name: {{ .Values.secretName | quote }}
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingressClass | quote }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.secretName | quote }}
spec:
  acme: 
    email: {{ .Values.adminEmail | quote }} 
    privateKeySecretRef:
      name: {{ .Values.secretName | quote }}
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: {{ .Values.ingressClass | quote }}